name: Release Installers for macOS

on:
  push:
    tags:
      - '*'

jobs:

  release-installers:

    runs-on: macos-14

    permissions:
      contents: write

    steps:

      - name: Install build dependencies.
        run: |
          brew update
          brew install cmake libpq postgresql@17

      - name: Check out our code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up a keychain for Apple code signing.
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          APP_CERTIFICATE_BASE64: ${{ secrets.APPLE_APP_CERTIFICATE_BASE64 }}
          INSTALLER_CERTIFICATE_BASE64: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_BASE64 }}
        run: |
          # Reconstitute text-encoded secrets as binary .p12 files.
          APP_CERTIFICATE_PATH=$RUNNER_TEMP/developerID_application.p12
          echo -n "$APP_CERTIFICATE_BASE64" | base64 --decode -o $APP_CERTIFICATE_PATH
          INSTALLER_CERTIFICATE_PATH=$RUNNER_TEMP/developerID_installer.p12
          echo -n "$INSTALLER_CERTIFICATE_BASE64" | base64 --decode -o $INSTALLER_CERTIFICATE_PATH

          # Create a new keychain for use in CI.
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

          # Add our certificates to the keychain.
          security import $APP_CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security import $INSTALLER_CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"

          # Allow codesign util and the current user to use this keychain for signing.
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Log info about this keychain for debugging.
          security find-identity -p basic -v

      - name: Build, sign, package, and notarize dlsh.
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          INSTALLER_CERT_ID: ${{ secrets.APPLE_INSTALLLER_CERT_ID }}
        run: |
          cmake -B build -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM="$TEAM_ID" \
            -D PROJECT_VERSION=${{ github.ref_name }} \
            -D CPACK_PRODUCTBUILD_COMPONENT_INSTALL=ON \
            -D CPACK_COMPONENTS_ALL="dlsh;dg"
          cmake --build build --config Release
          cpack -G productbuild --config build/CPackConfig.cmake
          productsign --sign "$INSTALLER_CERT_ID" dlsh-${{ github.ref_name }}-Darwin.pkg dlsh-${{ github.ref_name }}-Darwin-$(uname -m)-signed.pkg

          xcrun notarytool store-credentials --apple-id "$APPLE_ID" --team-id "$TEAM_ID" --password "$APPLE_APP_PASSWORD" "dlsh-signing"
          xcrun notarytool submit dlsh-${{ github.ref_name }}-Darwin-$(uname -m)-signed.pkg --keychain-profile "dlsh-signing" --wait
          xcrun stapler staple dlsh-${{ github.ref_name }}-Darwin-$(uname -m)-signed.pkg

      - name: Create a GitHub release for the current tag and package.
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./*-signed.pkg"
          body: libs, headers and dependencies for dlsh version ${{ github.ref_name }}
          generateReleaseNotes: true
          allowUpdates: true
